[project]
name = "saliencymapdemo"
version = "1.0.0"
description = "SaliencyMapDemo"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gradio>=5.29.1",
    "gradio-client>=1.10.1",
    "opencv-contrib-python>=4.11.0.86",
    "opencv-python>=4.11.0.86",
]
