[project]
name = "saliencymapdemo"
version = "0.0.13"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gradio>=5.13.1",
    "gradio-client>=1.6.0",
    "opencv-contrib-python>=4.11.0.86",
    "opencv-python>=4.11.0.86",
]
